title: Dev.Opera
url: http://dev.opera.com/
permalink: /:categories/:title/
future: false

markdown: kramdown
kramdown:
  auto_ids: true
  transliterated_header_ids: true

include:
- '.htaccess'
exclude:
- 'node_modules'
- 'Gruntfile.js'
- 'package.json'
- 'install.sh'
- 'README.md'
- 'LICENSE.md'
- 'CONTRIBUTING.md'
- '*.scss'

defaults:
  - scope:
      path: 'articles'
      type: 'post'
    values:
      category: 'articles'
      layout: 'entry'
      language: 'en'
  - scope:
      path: 'blog'
      type: 'post'
    values:
      category: 'blog'
      layout: 'entry'
      language: 'en'
  - scope:
      path: 'tv'
      type: 'post'
    values:
      category: 'tv'
      layout: 'entry'
      language: 'en'
