title: Dev.Opera
url: http://dev.opera.com/
permalink: /:categories/:title/
future: false

markdown: redcarpet
redcarpet:
  extensions: [
    "lax_spacing",
    "no_intra_emphasis",
    "strikethrough",
    "tables",
    "with_toc_data"
  ]

include:
- '.htaccess'
exclude:
- 'node_modules'
- 'Gruntfile.js'
- 'package.json'
- 'README.md'
- 'LICENSE.md'
- 'CONTRIBUTING.md'
- '*.scss'
